= Gollections

== Gollections

This is a set of utilities aimed at reducing boilerplate code when using link:./slice/api.go[slices], link:./map_/api.go[maps] and 
extending functionality by new collection implementations such as link:./collection/collection/mutable/omap/api.go[ordered map] or link:./collection/collection/mutable/oset/api.go[set].

Supports Go version 1.20.

For example, you want to group some link:./internal/examples/boilerplate/user_type.go[users] by their role names converted to lowercase:
[source,go]
----
include::../examples/boilerplate/user_data.go[lines=3..-1]
----

You can make clear code, extensive, but without dependencies:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_old_test.go[lines=11..33,indent=0]
----

Or you can write more compact code using the collections API, like so:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_new_test.go[lines=13..21,indent=0]
----

=== Installation

[source,console]
----
go get -u github.com/m4gshm/gollections
----

or 

[source,console]
----
go get -u github.com/m4gshm/gollections@HEAD
----

=== Main packages

All packages consists of functions placed in the package and subpackages aimed to make short aliases of that functions.
For example the function link:./slice/api.go#L459[slice.SortByOrdered] has aliases link:./slice/sort/api.go#L12[sort.By] and link:./slice/sort/api.go#L23[sort.Of].

==== link:./slice/api.go[slice] and link:./map_/api.go[map_]

Contains utility functions of link:./slice/api.go#L156[converting],  link:./slice/api.go#L379[filtering] (searching), link:./slice/api.go#L464[reducing], link:./map_/api.go#L90[cloning] elements of embedded slices and maps. The functions compute result in-place. For delayed computations see xref:loop-kvloop-and-breakable-versions-breakloop-breakkvloop[loops] or xref:collection-functions[collection functions]. 

[source,go]
----
include::../examples/boilerplate/slice_filter_convert_reduce_test.go[lines=13..24,indent=0]
----

More examples link:./internal/examples/sliceexamples/slice_examples_test.go[here] and link:./internal/examples/mapexamples/map_examples_test.go[here].

==== link:./collection/mutable/api.go[mutable] and link:./collection/immutable/api.go[immutable] collections

Provides implelentations of link:./collection/iface.go#L25[Vector], link:./collection/iface.go#L35[Set] and link:./collection/iface.go#L41[Map].

Mutables support content appending, updating and deleting (the ordered map implementation is not supported delete operations). +
Immutables are read-only datasets.

Detailed description of implementations xref:mutable-collections[below].

==== link:./predicate/api.go[predicate] and breakable link:./predicate/api.go[break/predicate]

Provides predicate builder api that used for filtering collection elements.

[source,go]
----
include::../examples/boilerplate/predicate_test.go[lines=17..20,indent=0]
----
[#loop]
==== link:./loop/api.go[loop], link:./kv/loop/api.go[kv/loop] and breakable versions link:./break/loop/api.go[break/loop], link:./break/kv/loop/api.go[break/kv/loop]

Low level iteration api based on ``next`` function.

[source,go]
----
include::../examples/loop/loop_filter_convert_reduce_test.go[lines=10..15,indent=0]
----

The function retrieves a next element from a dataset and returns ``ok==true`` if successful. +
The API in most cases is similar to the link:./slice/api.go[slice] API but with delayed computation which means that the methods don't compute a result but only return a loop provider. The loop provider is type with a ``Next`` method that returns a next processed element.

[source,go]
----
include::../examples/loop/loop_filter_convert_reduce_test.go[lines=17..22,indent=0]
----

Breakable loops additionaly have error returned value.

[source,go]
----
include::../examples/loop/breakloop/loop_filter_convert_reduce_test.go[lines=10..15,indent=0]
----

It is used for computations where an error may occur.

[source,go]
----
include::../examples/loop/breakloop/loop_filter_convert_reduce_test.go[lines=17..22,indent=0]
----

=== Mutable collections

Supports write operations (append, delete, replace).

  * link:./collection/mutable/vector/api.go[Vector] - the simplest based on built-in slice collection.

[source,go]
----
include::../examples/collection/mutable/vector.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/set/api.go[Set] - collection of unique items, prevents duplicates.

[source,go]
----
include::../examples/collection/mutable/set.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/map_/api.go[Map] - built-in map wrapper that supports xref:stream-functions[stream functions].

[source,go]
----
include::../examples/collection/mutable/map.go[lines=11..12,indent=0]
----

  * link:./collection/mutable/oset/api.go[OrderedSet] - collection of unique items, prevents duplicates, provides iteration in order of addition.

[source,go]
----
include::../examples/collection/mutable/oset.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/omap/api.go[OrderedMap] - same as the Map, but supports iteration in the order in which elements are added.

[source,go]
----
include::../examples/collection/mutable/omap.go[lines=11..15,indent=0]
----

==== Immutable containers

The same underlying interfaces but for read-only use cases.

=== Collection functions

There are three groups of operations:

* Immediate - retrieves the result in place (link:./collection/mutable/vector.go#L322[Sort], link:./collection/immutable/vector.go#L154[Reduce], link:./collection/immutable/vector.go#L111[Track], link:./collection/mutable/ordered/map.go#L182[TrackEach], link:./collection/immutable/vector.go#L122[For], link:./collection/immutable/ordered/map.go#L175[ForEach])
* Intermediate - only defines a computation (link:./collection/api.go#L17[Convert], link:./collection/immutable/ordered/set.go#L124[Filter], link:./collection/api.go#L36[Flatt], link:./collection/api.go#L69[Group]).
* Final - applies intermediates and retrieves a result (link:./collection/api.go#L75[First], link:./collection/immutable/ordered/set.go#L94[Slice], link:./collection/immutable/ordered/set.go#L146[Reduce])

Intermediates should wrap one by one to make a lazy computation chain that can be applied to the latest final operation.

[source,go]
----
include::../examples/collection/functions/collection_functions_test.go[lines=14..33,indent=0]
----
