= Gollections

== Gollections

Golang generic containers and functions.

Supports Go version 1.20 or higher.

=== Installation

[source,console]
----
go get -u github.com/m4gshm/gollections
----

or 

[source,console]
----
go get -u github.com/m4gshm/gollections@HEAD
----

=== Main packages

==== Slices - link:./slice/api.go[github.com/m4gshm/gollections/slice]

The package provides helper subpackages and functions for using with slices. +
Most helpers organized as pair of a main function and short aliases in a subpackage. For example the function link:./slice/api.go#L247[slice.SortByOrdered] has aliases link:./slice/sort/api.go#L12[sort.By] and link:./slice/sort/api.go#L23[sort.Of].

Usage examples link:./internal/examples/sliceexamples/slice_examples_test.go[here].


==== Loops - link:./loop/api.go[loop], link:./kv/loop/api.go[kv/loop]

TODO

==== Maps - link:./map_/api.go[github.com/m4gshm/gollections/map_]

The package provides helper subpackages and functions for using with maps. +

Usage examples link:./internal/examples/mapexamples/map_examples_test.go[here].

==== Mutable containers

Supports write operations (append, delete, replace).

  * link:./mutable/vector/api.go[Vector] - the simplest based on built-in slice collection.
  * link:./mutable/set/api.go[Set] - collection of unique items, prevents duplicates.
  * link:./mutable/map_/api.go[Map] - built-in map wrapper that supports link:#container-functions[container functions].
  * link:./mutable/oset/api.go[OrderedSet] - collection of unique items, prevents duplicates, provides iteration in order of addition.
  * link:./mutable/omap/api.go[OrderedMap] - same as the link:./mutable/map_/api.go[Map], but supports iteration in the order in which elements are added.
  * link:./mutable/sync/map.go[sync.Map] - generic wrapper of built-in embedded sync.Map.

==== Immutable containers

The same interfaces as in the mutable package but for read-only purposes.

==== Containers creating

===== Immutable

[source,go]
----
include::../examples/constructors.go[]
----

where link:./immutable/vector/api.go[vector], link:./immutable/set/api.go[set], link:./immutable/oset/api.go[oset], link:./immutable/map_/api.go[map_], link:./immutable/omap/api.go[omap] are packages from link:./immutable/[github.com/m4gshm/gollections/immutable] and link:./k/v.go[k.V] is the method V from the package link:./k/[k]

===== Mutable

[source,go]
----
include::../examples/constructors_mutable.go[]
----

where link:./mutable/vector/api.go[vector], link:./mutable/set/api.go[set], link:./mutable/oset/api.go[oset], link:./mutable/map_/api.go[map_], link:./mutable/omap/api.go[omap] are packages from link:./mutable/[github.com/m4gshm/gollections/mutable] and link:./k/v.go[k.V] is the method V from the package link:./k/[k]

=== Stream functions

There are three groups of operations:

* Immediate - retrieves the result in place (link:./immutable/vector.go#L112[Sort], link:./immutable/vector.go#L107[Reduce] (of containers), link:./immutable/vector.go#L81[Track], link:./immutable/ordered/map.go#L136[TrackEach], link:./immutable/vector.go#L89[For], link:./immutable/ordered/map.go#L144[ForEach])
* Intermediate - only defines a computation (link:./it/api.go#L17[Wrap], link:./c/op/api.go#L11[Map], link:./c/op/api.go#L21[Flatt], link:./c/op/api.go#L33[Filter], link:./c/op/api.go#L53[Group]).
* Final - applies intermediates and retrieves a result (link:./it/api.go#L75[ForEach], link:./it/api.go#L65[Slice], link:./it/api.go#L55[Reduce] (of iterators))

Intermediates should wrap one by one to make a lazy computation chain that can be applied to the latest final operation.

[source,go]
----
//Example 'filter', 'map', 'reduce' for an iterative container of 'items'

var items immutable.Vector[Item]

var (
    condition = func(item Item) bool { ... }
    max       = func(attribute1 Attribute, attribute2 Attribute) Attribute { ... }
) 

maxItemAttribute := it.Reduce(it.Convert(c.Filer(items, condition), Item.GetAttribute), max)
----

Functions grouped into packages by applicable type (link:./c/api.go[container], link:./c/map_/api.go[map], link:./it/api.go[iterator], link:slice/api.go[slice])

=== Additional packages

==== link:./c/iface.go[Common interfaces]

Iterator, Iterable, Container, Vector, Map, Set and so on.

==== link:./c/op/api.go[Iterable container API]
Declarative style API over 'Iterable' interface. Based on 'Iterator API' (see below).

==== link:./it/api.go[Iterator API]
Declarative style API over 'Iterator' interface. 

=== Examples

[source,go]
----
include::../examples/examples_test.go[]
----
