= Gollections

== Gollections

Gollections is set of functions for link:#slices[slices], link:#maps[maps] and additional implementations of data structures such as link:#mutable-collections[ordered map] or link:#mutable-collections[set] aimed to reduce boilerplate code.

Supports Go version 1.22.

For example, it's need to group some link:./internal/examples/boilerplate/user_type.go[users] by their role names converted to lowercase:
[source,go]
----
include::../examples/boilerplate/user_data.go[lines=3..-1]
----

You can make clear code, extensive, but without dependencies:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_old_test.go[lines=11..26,indent=0]
----

Or you can write more compact code using the collections API, like:
[source,go]
----
import (
    "github.com/m4gshm/gollections/slice/convert"
    "github.com/m4gshm/gollections/slice/group"
)
include::../examples/boilerplate/slice_namesbyRole_new_test.go[lines=14..20,indent=0]
----

=== Installation

[source,console]
----
go get -u github.com/m4gshm/gollections
----

=== Slices

[source,go]
----
include::../examples/boilerplate/slice_filter_convert_reduce_test.go[lines=14..20,indent=0]
----

In the example is used only small set of slice functions as link:#slicefilter[slice.Filter], link:#sliceconv[slice.Conv] link:#sliceconvert#[slice.Convert], and link:#slicereduce[slice.Reduce]. More you can look in the link:./slice/api.go[slice] package.

==== Shortcut packages

[source,go]
----
include::../examples/boilerplate/slice_filter_convert_reduce_short_test.go[lines=18..20,indent=0]
----

This is a shorter version of the previous example that used short aliases link:#sumof[sum.Of] and link:#operations-chain-functions[filter.AndConvert]. More shortcuts you can find by exploring slices link:./slice[subpackages].

*Be careful* when use several slice functions subsequently like [source,go]`slice.Filter(slice.Convert(...))`. This can lead to unnecessary RAM consumption. Consider link:#loop-kvloop-and-breakable-versions-breakloop-breakkvloop[loop] instead of slice API.

==== Main slice functions
===== Instantiators
====== slice.Of
[source,go]
----
include::../examples/sliceexamples/slice_Of_test.go[lines=11..13,indent=0]
----
====== range_.Of
[source,go]
----
import "github.com/m4gshm/gollections/slice/range_"
include::../examples/sliceexamples/range_Of_test.go[lines=11..15,indent=0]
----
====== range_.Closed
[source,go]
----
include::../examples/sliceexamples/range_Closed_test.go[lines=12..16,indent=0]
----
===== Sorters
====== sort.Asc, sort.Desc 
[source,go]
----
// sorting in-place API
import "github.com/m4gshm/gollections/slice/sort"
include::../examples/sliceexamples/sort_Asc_Desc_test.go[lines=12..15,indent=0]
----
====== sort.By, sort.ByDesc
[source,go]
----
// sorting copied slice API does not change the original slice
import "github.com/m4gshm/gollections/slice/clone/sort"

include::../examples/sliceexamples/data_users_test.go[lines=3..10,indent=0]
include::../examples/sliceexamples/clone_sort_By_test.go[lines=12..18,indent=0]
----
===== Collectors
====== group.Of
[source,go]
----
import (
    "github.com/m4gshm/gollections/convert/as"
    "github.com/m4gshm/gollections/expr/use"
    "github.com/m4gshm/gollections/slice/group"
)
include::../examples/sliceexamples/group_Of_test.go[lines=16..22,indent=0]
----
====== group.Order
[source,go]
----
import (
    "github.com/m4gshm/gollections/convert/as"
    "github.com/m4gshm/gollections/expr/use"
    "github.com/m4gshm/gollections/slice/group"
)
include::../examples/sliceexamples/group_Order_test.go[lines=16..23,indent=0]
----
====== group.ByMultipleKeys
[source,go]
----
import (
    "github.com/m4gshm/gollections/slice/convert"
    "github.com/m4gshm/gollections/slice/group"
)
include::../examples/boilerplate/slice_namesbyRole_new_test.go[lines=14..19,indent=0]
----
====== slice.Map, slice.AppendMap
[source,go]
----
import "github.com/m4gshm/gollections/slice"
include::../examples/sliceexamples/slice_ToMap_test.go[lines=11..15,indent=0]
----
====== slice.MapOrder, slice.AppendMapOrder
[source,go]
----
import "github.com/m4gshm/gollections/slice"
include::../examples/sliceexamples/slice_ToMapOrder_test.go[lines=12..17,indent=0]
----
====== slice.MapResolv, slice.AppendMapResolv
[source,go]
----
import (
    "github.com/m4gshm/gollections/map_/resolv"
    "github.com/m4gshm/gollections/op"
    "github.com/m4gshm/gollections/slice"
)
include::../examples/sliceexamples/slice_ToMapResolv_test.go[lines=14..22,indent=0]
----
===== Reducers
====== sum.Of
[source,go]
----
import "github.com/m4gshm/gollections/op/sum"
include::../examples/sliceexamples/sum_Of_test.go[lines=12..14,indent=0]
----
====== slice.Reduce
[source,go]
----
include::../examples/sliceexamples/slice_Reduce_test.go[lines=12..15,indent=0]
----
====== slice.Accum
[source,go]
----
import (
	"github.com/m4gshm/gollections/op"
	"github.com/m4gshm/gollections/slice"
)
include::../examples/sliceexamples/slice_Accum_test.go[lines=13..16,indent=0]
----
====== slice.First
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/more"
    "github.com/m4gshm/gollections/slice"
)
include::../examples/sliceexamples/slice_First_test.go[lines=13..15,indent=0]
----
====== slice.Last
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/less"
    "github.com/m4gshm/gollections/slice"
)
include::../examples/sliceexamples/slice_Last_test.go[lines=13..15,indent=0]
----
===== Element converters
====== slice.Convert
[source,go]
----
include::../examples/sliceexamples/slice_Convert_test.go[lines=13..16,indent=0]
----
====== slice.Conv
[source,go]
----
include::../examples/sliceexamples/slice_Conv_test.go[lines=13..16,indent=0]
----
===== Slice converters
====== slice.Filter
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/exclude"
    "github.com/m4gshm/gollections/predicate/one"
    "github.com/m4gshm/gollections/slice"
)
include::../examples/sliceexamples/slice_Filter.go[lines=14..17,indent=0]
----
====== slice.Flat
[source,go]
----
import (
    "github.com/m4gshm/gollections/convert/as"
    "github.com/m4gshm/gollections/slice"
)
include::../examples/sliceexamples/slice_Flat_test.go[lines=13..16,indent=0]
----
===== Operations chain functions
* convert.AndReduce, conv.AndReduce 
* convert.AndFilter 
* filter.AndConvert

These functions combine converters, filters and reducers.

=== Maps
==== Main map functions
===== Instantiators
====== clone.Of
[source,go]
----
import "github.com/m4gshm/gollections/map_/clone"
include::../examples/mapexamples/clone_Of_test.go[lines=13..28,indent=0]
----
====== clone.Deep
[source,go]
----
import "github.com/m4gshm/gollections/map_/clone"
include::../examples/mapexamples/clone_Deep_test.go[lines=13..30,indent=0]
----
===== Collectors
====== map_.Slice
[source,go]
----
include::../examples/mapexamples/map_ToSlice_test.go[lines=19..24,indent=0]
----
====== map_.Keys, map_.Values, map_.KeysConvert, map_.ValuesConvert
[source,go]
----
include::../examples/mapexamples/map_Keys_Values_test.go[lines=15..23,indent=0]
----
===== Element converters
====== map_.ConvertKeys
[source,go]
----
include::../examples/mapexamples/map_ConvertKeys_test.go[lines=17..22,indent=0]
----
====== map_.ConvertValues
[source,go]
----
include::../examples/mapexamples/map_ConvertValues_test.go[lines=17..22,indent=0]
----
====== map_.Convert
[source,go]
----
include::../examples/mapexamples/map_Convert_test.go[lines=17..22,indent=0]
----
====== map_.Conv
[source,go]
----
include::../examples/mapexamples/map_Conv_test.go[lines=17..22,indent=0]
----

[#seq]
=== link:./seq/api.go[seq], link:./seq2/api.go[seq2]

API extends rangefunc iterator types `seq.Seq[V]`, `seq.Seq2[K,V]` with utility functions kit.

[source,go]
----
include::../examples/seqexamples/seq_filter_convert_reduce_test.go[lines=13..17,indent=0]
----
or
[source,go]
----
include::../examples/seqexamples/seq2_filter_convert_reduce_test.go[lines=14..17,indent=0]
----
==== Sequence API

To use any collection or loop as a rangefunc sequecne just call link:#iterating-over-collections[All] method of that one.

In many cases the API likes the link:#loop-kvloop-and-breakable-versions-breakloop-breakkvloop[loop] API.

===== Instantiators
====== seq.Of, seq2.Of, seq2.OfMap
[source,go]
----
import(
    "github.com/m4gshm/gollections/seq"
    "github.com/m4gshm/gollections/seq2"
)
include::../examples/seqexamples/seq_Of_test.go[lines=14..19,indent=0]
----
===== Collectors
====== seq.Slice
[source,go]
----
include::../examples/seqexamples/seq_Slice_test.go[lines=12..16,indent=0]
----
====== seq2.Group, seq2.Map
[source,go]
----
import (
    "iter"

	"github.com/m4gshm/gollections/expr/use"
	"github.com/m4gshm/gollections/seq"
	"github.com/m4gshm/gollections/seq2"
	"github.com/m4gshm/gollections/slice"
	"github.com/m4gshm/gollections/slice/sort"
)
include::../examples/seqexamples/seq2_Group_test.go[lines=17..25,indent=0]
----
===== Reducers
====== seq.Reduce
[source,go]
----
include::../examples/seqexamples/seq_Reduce_test.go[lines=12..15,indent=0]
----
====== seq.ReduceOK
[source,go]
----
include::../examples/seqexamples/seq_ReduceOK_test.go[lines=12..21,indent=0]
----
====== seq.First
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/more"
    "github.com/m4gshm/gollections/seq"
)
include::../examples/seqexamples/seq_First_test.go[lines=13..15,indent=0]
----
===== Element converters
====== seq.Convert
[source,go]
----
include::../examples/seqexamples/seq_Convert_test.go[lines=12..15,indent=0]
----
====== seq.Conv
[source,go]
----
include::../examples/seqexamples/seq_Conv_test.go[lines=14..17,indent=0]
----
===== Sequence converters
====== seq.Filter
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/exclude"
    "github.com/m4gshm/gollections/predicate/one"
    "github.com/m4gshm/gollections/seq"
)
include::../examples/seqexamples/seq_Filter.go[lines=14..20,indent=0]
----
====== seq.Flat
[source,go]
----
import (
    "github.com/m4gshm/gollections/convert/as"
    "github.com/m4gshm/gollections/seq"
)
include::../examples/seqexamples/seq_Flat_test.go[lines=13..16,indent=0]
----

[#loop]
=== link:./loop/api.go[loop], link:./kv/loop/api.go[kv/loop] and breakable versions link:./break/loop/api.go[break/loop], link:./break/kv/loop/api.go[break/kv/loop]

Legacy iterators API based on the following functions:

[source,go]
----
include::../examples/loopexamples/type.go[lines=2..9,indent=0]
----

The `Loop` function returns a next element from a dataset and returns ``ok==true`` on success. ``ok==false`` means there are no more elements in the dataset. +
The `KVLoop` behaves similar but returns key/value pairs. +

[source,go]
----
include::../examples/loopexamples/loop_filter_convert_reduce_test.go[lines=13..17,indent=0]
----

`BreakLoop` and `BreakKVLoop` are used for sources that can issue an error.

[source,go]
----
include::../examples/loopexamples/breakloop/loop_filter_convert_reduce_test.go[lines=13..16,indent=0]
----

The API in most cases is similar to the link:./slice/api.go[slice] API but with delayed computation which means that the methods don't compute a result but only return a loop provider. The loop provider is type with a ``Next`` method that returns a next processed element.

==== Main loop functions
===== Instantiators
====== loop.Of, loop.S
[source,go]
----
import "github.com/m4gshm/gollections/loop"
include::../examples/loopexamples/loop_Of_loop_S_test.go[lines=12..17,indent=0]
----
====== range_.Of
[source,go]
----
import "github.com/m4gshm/gollections/loop/range_"
include::../examples/loopexamples/range_Of_test.go[lines=11..15,indent=0]
----
====== range_.Closed
[source,go]
----
include::../examples/loopexamples/range_Closed_test.go[lines=12..16,indent=0]
----
===== Collectors
====== loop.Slice
[source,go]
----
include::../examples/loopexamples/loop_Slice_test.go[lines=12..16,indent=0]
----
====== group.Of
[source,go]
----
import (
    "github.com/m4gshm/gollections/convert/as"
    "github.com/m4gshm/gollections/expr/use"
    "github.com/m4gshm/gollections/loop"
    "github.com/m4gshm/gollections/loop/group"
)
include::../examples/loopexamples/group_Of_test.go[lines=17..23,indent=0]
----
====== loop.Map, loop.MapResolv
[source,go]
----
import (
    "github.com/m4gshm/gollections/map_/resolv"
    "github.com/m4gshm/gollections/op"
    "github.com/m4gshm/gollections/loop"
)
include::../examples/loopexamples/loop_ToMapResolv_test.go[lines=14..22,indent=0]
----
===== Reducers
====== sum.Of
[source,go]
----
import (
    "github.com/m4gshm/gollections/loop"
	"github.com/m4gshm/gollections/loop/sum"
)
include::../examples/loopexamples/sum_Of_test.go[lines=13..15,indent=0]
----
====== loop.Reduce
[source,go]
----
include::../examples/loopexamples/loop_Reduce_test.go[lines=12..15,indent=0]
----
====== loop.ReduceOK
[source,go]
----
include::../examples/loopexamples/loop_ReduceOK_test.go[lines=12..21,indent=0]
----
====== loop.Accum
[source,go]
----
import (
	"github.com/m4gshm/gollections/loop"
	"github.com/m4gshm/gollections/op"
)
include::../examples/loopexamples/loop_Accum_test.go[lines=13..16,indent=0]
----
====== loop.First
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/more"
    "github.com/m4gshm/gollections/loop"
)
include::../examples/loopexamples/loop_First_test.go[lines=13..15,indent=0]
----
===== Element converters
====== loop.Convert
[source,go]
----
include::../examples/loopexamples/loop_Convert_test.go[lines=12..15,indent=0]
----
====== loop.Conv
[source,go]
----
include::../examples/loopexamples/loop_Conv_test.go[lines=13..16,indent=0]
----
===== Loop converters
====== loop.Filter
[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/exclude"
    "github.com/m4gshm/gollections/predicate/one"
    "github.com/m4gshm/gollections/loop"
)
include::../examples/loopexamples/loop_Filter.go[lines=14..20,indent=0]
----
====== loop.Flat
[source,go]
----
import (
    "github.com/m4gshm/gollections/convert/as"
    "github.com/m4gshm/gollections/loop"
)
include::../examples/loopexamples/loop_Flat_test.go[lines=13..16,indent=0]
----
===== Operations chain functions
* convert.AndReduce, conv.AndReduce 
* convert.AndFilter 
* filter.AndConvert

These functions combine converters, filters and reducers.

==== Iterating over loops
* (only for go 1.22) Using rangefunc `All` like:

[source,go]
----
include::../examples/loopexamples/loop_iterating_go_1_22_test.go[lines=12..16,indent=0]
----
don't forget exec `go env -w GOEXPERIMENT=rangefunc` before compile.

* Using `for` statement like:

[source,go]
----
include::../examples/loopexamples/loop_iterating_test.go[lines=11..16,indent=0]
----

* or

[source,go]
----
include::../examples/loopexamples/loop_iterating_test.go[lines=20..24,indent=0]
----

* `ForEach` method

[source,go]
----
include::../examples/loopexamples/loop_iterating_test.go[lines=28..30,indent=0]
----

* or `For` method that can be aborted by returning `Break` for expected completion, or another error otherwise.

[source,go]
----
include::../examples/loopexamples/loop_iterating_test.go[lines=34..42,indent=0]
----

=== Data structures
==== link:./collection/mutable/api.go[mutable] and link:./collection/immutable/api.go[immutable] collections

Provides implelentations of link:./collection/iface.go#L25[Vector], link:./collection/iface.go#L35[Set] and link:./collection/iface.go#L41[Map].

Mutables support content appending, updating and deleting (the ordered map implementation is not supported delete operations). +
Immutables are read-only datasets.

Detailed description of implementations xref:mutable-collections[below].

=== Additional API

==== link:./predicate/api.go[predicate] and breakable link:./predicate/api.go[break/predicate]

Provides predicate builder api that used for filtering collection elements.

[source,go]
----
import (
    "github.com/m4gshm/gollections/predicate/where"
    "github.com/m4gshm/gollections/slice"
)
include::../examples/boilerplate/predicate_test.go[lines=16..18,indent=0]
----

==== Expressions: link:./expr/use/api.go[use.If], link:./expr/get/api.go[get.If], link:#firstof[first.Of], link:#lastof[last.Of]

Aimed to evaluate a value using conditions. May cause to make code shorter by not in all cases. +
As example:

[source,go]
----
import "github.com/m4gshm/gollections/expr/use"
include::../examples/boilerplate/expr_use_test.go[lines=15..22,indent=0]
----

instead of:

[source,go]
----
include::../examples/boilerplate/expr_use_test.go[lines=27..38,indent=0]
----

===== first.Of
[source,go]
----
import (
    "github.com/m4gshm/gollections/expr/first"
    "github.com/m4gshm/gollections/predicate/more"
)
include::../examples/expressionexamples/first_Of_test.go[lines=13..15,indent=0]
----
===== last.Of
[source,go]
----
import (
    "github.com/m4gshm/gollections/expr/last"
    "github.com/m4gshm/gollections/predicate/less"
)
include::../examples/expressionexamples/last_Of_test.go[lines=13..15,indent=0]
----

=== Mutable collections

Supports write operations (append, delete, replace).

  * link:./collection/mutable/vector/api.go[Vector] - the simplest based on built-in slice collection.

[source,go]
----
include::../examples/collection/mutable/vector.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/set/api.go[Set] - collection of unique items, prevents duplicates.

[source,go]
----
include::../examples/collection/mutable/set.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/map_/api.go[Map] - built-in map wrapper that supports xref:stream-functions[stream functions].

[source,go]
----
include::../examples/collection/mutable/map.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/oset/api.go[OrderedSet] - collection of unique items, prevents duplicates, provides iteration in order of addition.

[source,go]
----
include::../examples/collection/mutable/oset.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/omap/api.go[OrderedMap] - same as the Map, but supports iteration in the order in which elements are added.

[source,go]
----
include::../examples/collection/mutable/omap.go[lines=11..15,indent=0]
----

==== Immutable collections

The same underlying interfaces but for read-only use cases.

==== Iterating over collections
* (only for go 1.22) Using rangefunc `All` like:

[source,go]
----
include::../examples/collection/collection_iterating_go_1_22_test.go[lines=13..18,indent=0]
----
* Using `for` statement like:

[source,go]
----
include::../examples/collection/collection_iterating_test.go[lines=12..18,indent=0]
----

* or

[source,go]
----
include::../examples/collection/collection_iterating_test.go[lines=22..27,indent=0]
----

* `ForEach` method

[source,go]
----
include::../examples/collection/collection_iterating_test.go[lines=31..34,indent=0]
----

* or `For` method that can be aborted by returning `Break` for expected completion, or another error otherwise.

[source,go]
----
include::../examples/collection/collection_iterating_test.go[lines=38..47,indent=0]
----
