= Gollections

== Gollections

This is a development kit aimed at reducing boilerplate code when using link:./slice/api.go[slices], link:./map_/api.go[maps] and 
extending functionality by new collection implementations such as link:./collection/collection/mutable/omap/api.go[ordered map] or link:./collection/collection/mutable/oset/api.go[set].

Supports Go version 1.20.

For example, you want to group some users by their role names converted to lowercase:
[source,go]
----
include::../examples/boilerplate/user_data.go[lines=3..-1]
----

You can make clear code, extensive, but without dependencies:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_old.go[lines=11..33]
----


Or using the devkit you can write more compact code like this:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_new.go[lines=13..21]
----

=== Installation

[source,console]
----
go get -u github.com/m4gshm/gollections
----

or 

[source,console]
----
go get -u github.com/m4gshm/gollections@HEAD
----

=== Main packages

All packages consists of functions placed in the package and subpackages aimed to make short aliases of that functions.
For example the function link:./slice/api.go#L459[slice.SortByOrdered] has aliases link:./slice/sort/api.go#L12[sort.By] and link:./slice/sort/api.go#L23[sort.Of].


==== link:./slice/api.go[slice] and link:./map_/api.go[map_]

Contains utility functions of link:./slice/api.go#L156[converting],  link:./slice/api.go#L379[filtering] (searching), link:./slice/api.go#L464[reducing], link:./map_/api.go#L90[cloning] elements of embedded slices and maps.

Usage examples link:./internal/examples/sliceexamples/slice_examples_test.go[here] and link:./internal/examples/mapexamples/map_examples_test.go[here].

==== link:./collection/mutable/api.go[mutable] and link:./collection/immutable/api.go[immutable] collections

Provides implelentations of link:./collection/iface.go#L25[Vector], link:./collection/iface.go#L35[Set] and link:./collection/iface.go#L41[Map].

Mutables support content appending, updating and deleting (the ordered map implementation is not supported delete operations).
Immutables are read-only datasets.

Detailed description of implementations below.

==== link:./predicate/api.go[predicate] and breakable link:./predicate/api.go[break/predicate]

Provides predicate builder api that used for filtering collection elements.

==== link:./loop/api.go[loop], link:./kv/loop/api.go[kv/loop] and breakable versions link:./break/loop/api.go[break/loop], link:./break/kv/loop/api.go[break/kv/loop]

TODO


==== Short aliases for collection constructors

TODO

==== Mutable collections

Supports write operations (append, delete, replace).

  * link:./collection/mutable/vector/api.go[Vector] - the simplest based on built-in slice collection.
[source,go]
----
include::../examples/collection/mutable/vector.go[lines=10..11]
----
  * link:./collection/mutable/set/api.go[Set] - collection of unique items, prevents duplicates.
[source,go]
----
include::../examples/collection/mutable/set.go[lines=10..11]
----
  * link:./collection/mutable/map_/api.go[Map] - built-in map wrapper that supports link:#container-functions[container functions].
[source,go]
----
include::../examples/collection/mutable/map.go[lines=11..12]
----
  * link:./collection/mutable/oset/api.go[OrderedSet] - collection of unique items, prevents duplicates, provides iteration in order of addition.
[source,go]
----
include::../examples/collection/mutable/oset.go[lines=10..11]
----
  * link:./collection/mutable/omap/api.go[OrderedMap] - same as the link:./collection/mutable/map_/api.go[Map], but supports iteration in the order in which elements are added.
----
include::../examples/collection/mutable/omap.go[lines=11..12]
----

==== Immutable containers

The same interfaces as in the mutable package but for read-only purposes.

==== Containers creating
===== Mutable

[source,go]
----
include::../examples/constructors_mutable.go[]
----

where link:./collection/mutable/vector/api.go[vector], link:./collection/mutable/set/api.go[set], link:./collection/mutable/oset/api.go[oset], link:./collection/mutable/map_/api.go[map_], link:./collection/mutable/omap/api.go[omap] are packages from link:./collection/mutable/[github.com/m4gshm/gollections/collection/mutable] and link:./k/v.go[k.V] is the method V from the package link:./k/[k]

=== Stream functions

There are three groups of operations:

* Immediate - retrieves the result in place (link:./collection/immutable/vector.go#L112[Sort], link:./collection/immutable/vector.go#L107[Reduce] (of containers), link:./collection/immutable/vector.go#L81[Track], link:./collection/immutable/ordered/map.go#L136[TrackEach], link:./collection/immutable/vector.go#L89[For], link:./collection/immutable/ordered/map.go#L144[ForEach])
* Intermediate - only defines a computation (link:./it/api.go#L17[Wrap], link:./c/op/api.go#L11[Map], link:./c/op/api.go#L21[Flatt], link:./c/op/api.go#L33[Filter], link:./c/op/api.go#L53[Group]).
* Final - applies intermediates and retrieves a result (link:./it/api.go#L75[ForEach], link:./it/api.go#L65[Slice], link:./it/api.go#L55[Reduce] (of iterators))

Intermediates should wrap one by one to make a lazy computation chain that can be applied to the latest final operation.

[source,go]
----
//TODO
----
