= Gollections

== Gollections

Gollections is set of functions for link:#slces#[slices], link:#maps[maps] and additional implementations of data structures such as link:#mutable-collections[ordered map] or link:#mutable-collections[set] aimed to reduce boilerplate code.

Supports Go version 1.21.

For example, it's need to group some link:./internal/examples/boilerplate/user_type.go[users] by their role names converted to lowercase:
[source,go]
----
include::../examples/boilerplate/user_data.go[lines=3..-1]
----

You can make clear code, extensive, but without dependencies:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_old_test.go[lines=11..30,indent=0]
----

Or you can write more compact code using the collections API, like:
[source,go]
----
include::../examples/boilerplate/slice_namesbyRole_new_test.go[lines=13..21,indent=0]
----

=== Installation

[source,console]
----
go get -u github.com/m4gshm/gollections
----


=== Slices

[source,go]
----
include::../examples/boilerplate/slice_filter_convert_reduce_test.go[lines=15..22,indent=0]
----

In the example is used only small set of slice functions as link:#slice-filter[slice.Filter], link:#slice-conv[Conv] link:./slice/api.go#L166[Convert], and link:#slice-reduce[Reduce]. More you can look in the link:./slice/api.go[slice] package.

==== Shortcut packages

[source,go]
----
include::../examples/boilerplate/slice_filter_convert_reduce_short_test.go[lines=18..20,indent=0]
----

This is a shorter version of the previous example that used short aliases link:#sum-of[sum.Of] and link:#filter-andonvert[filter.AndConvert].

===== Brief of usage

[source,go]
----
include::../examples/boilerplate/slice_shortcuts_test.go[lines=18..33,indent=0]
----

More shortcuts you can find by exploring slices link:./slice[subpackages].

==== Main slice functions

===== slice.Of
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=141..144,indent=0]
----
===== sort.Asc
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=149..152,indent=0]
----
===== sort.Desc 
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=157..160,indent=0]
----
===== sort.By (used User struct from above examples)
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=90..99,indent=0]
----
===== sort.ByDesc
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=99..102,indent=0]
----
===== sum.Of
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=324..327,indent=0]
----
===== range_.Of
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=341..352,indent=0]
----
===== range_.Closed
[source,go]
----
include::../examples/sliceexamples/slice_examples_test.go[lines=359..370,indent=0]
----

===== first.Of
===== last.Of

===== convert.AndReduce
===== conv.AndReduce
===== convert.AndConvert
===== convert.AndFilter
===== filter.AndConvert
===== filter.ConvertFilter
===== slice.ToMap
===== slice.ToMapResolv
===== group.Of
===== group.ByMultiple
===== group.ByMultipleKeys
===== group.ByMultipleValues

=== Maps

[source,go]
----
include::../examples/boilerplate/map_filter_convert_reduce_test.go[lines=16..45,indent=0]
----

More shortcuts are link:./map_[here].

==== Main map functions (TODO)

* creating - map_.Of, clone.Of, map_.DeepClone
* extract keys, values - map_.Keys, map_.Values
* converting, filtering, summarizing - map_.Convert, map_.ConvertKeys, map_.ConvertValues, map_.ToSlice, map_.Reduce
* versions of aboves with possible result errors - map_.Conv


=== Data structures

==== link:./collection/mutable/api.go[mutable] and link:./collection/immutable/api.go[immutable] collections

Provides implelentations of link:./collection/iface.go#L25[Vector], link:./collection/iface.go#L35[Set] and link:./collection/iface.go#L41[Map].

Mutables support content appending, updating and deleting (the ordered map implementation is not supported delete operations). +
Immutables are read-only datasets.

Detailed description of implementations xref:mutable-collections[below].

=== Additional API

==== link:./predicate/api.go[predicate] and breakable link:./predicate/api.go[break/predicate]

Provides predicate builder api that used for filtering collection elements.

[source,go]
----
include::../examples/boilerplate/predicate_test.go[lines=17..20,indent=0]
----
[#loop]
==== link:./loop/api.go[loop], link:./kv/loop/api.go[kv/loop] and breakable versions link:./break/loop/api.go[break/loop], link:./break/kv/loop/api.go[break/kv/loop]

Low level iteration api based on ``next`` function.

[source,go]
----
include::../examples/loop/loop_filter_convert_reduce_test.go[lines=10..15,indent=0]
----

The function retrieves a next element from a dataset and returns ``ok==true`` if successful. +
The API in most cases is similar to the link:./slice/api.go[slice] API but with delayed computation which means that the methods don't compute a result but only return a loop provider. The loop provider is type with a ``Next`` method that returns a next processed element.

[source,go]
----
include::../examples/loop/loop_filter_convert_reduce_test.go[lines=17..22,indent=0]
----

Breakable loops additionaly have error returned value.

[source,go]
----
include::../examples/loop/breakloop/loop_filter_convert_reduce_test.go[lines=10..15,indent=0]
----

It is used for computations where an error may occur.

[source,go]
----
include::../examples/loop/breakloop/loop_filter_convert_reduce_test.go[lines=17..22,indent=0]
----

==== Expressions: link:./expr/use/api.go[use], link:./expr/get/api.go[get], link:./expr/first/api.go[first], link:./expr/last/api.go[last]

Aimed to evaluate a value using conditions. May cause to make code shorter by not in all cases. +
As example:

[source,go]
----
include::../examples/boilerplate/expr_use_test.go[lines=14..21,indent=0]
----

instead of:

[source,go]
----
include::../examples/boilerplate/expr_use_test.go[lines=27..38,indent=0]
----


=== Mutable collections

Supports write operations (append, delete, replace).

  * link:./collection/mutable/vector/api.go[Vector] - the simplest based on built-in slice collection.

[source,go]
----
include::../examples/collection/mutable/vector.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/set/api.go[Set] - collection of unique items, prevents duplicates.

[source,go]
----
include::../examples/collection/mutable/set.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/map_/api.go[Map] - built-in map wrapper that supports xref:stream-functions[stream functions].

[source,go]
----
include::../examples/collection/mutable/map.go[lines=11..12,indent=0]
----

  * link:./collection/mutable/oset/api.go[OrderedSet] - collection of unique items, prevents duplicates, provides iteration in order of addition.

[source,go]
----
include::../examples/collection/mutable/oset.go[lines=10..11,indent=0]
----

  * link:./collection/mutable/omap/api.go[OrderedMap] - same as the Map, but supports iteration in the order in which elements are added.

[source,go]
----
include::../examples/collection/mutable/omap.go[lines=11..15,indent=0]
----

==== Immutable containers

The same underlying interfaces but for read-only use cases.

=== Collection functions

There are three groups of operations:

* Immediate - retrieves the result in place (link:./collection/mutable/vector.go#L322[Sort], link:./collection/immutable/vector.go#L154[Reduce], link:./collection/immutable/vector.go#L111[Track], link:./collection/mutable/ordered/map.go#L182[TrackEach], link:./collection/immutable/vector.go#L122[For], link:./collection/immutable/ordered/map.go#L175[ForEach])
* Intermediate - only defines a computation (link:./collection/api.go#L17[Convert], link:./collection/immutable/ordered/set.go#L124[Filter], link:./collection/api.go#L36[Flatt], link:./collection/api.go#L69[Group]).
* Final - applies intermediates and retrieves a result (link:./collection/api.go#L75[First], link:./collection/immutable/ordered/set.go#L94[Slice], link:./collection/immutable/ordered/set.go#L146[Reduce])

Intermediates should wrap one by one to make a lazy computation chain that can be applied to the latest final operation.

[source,go]
----
include::../examples/collection/functions/collection_functions_test.go[lines=14..33,indent=0]
----
