name: Run Tests

on:
  push:
    branches:
      - master**
      - master
      - main
      - dev
      - "dev**"
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  # pull_request:
  #   branches:
  #     - master
  #     - main
  #     - dev
  #     - "dev**"
  #     - "releases/**"
  #     - "feature/**"
  #     - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Task
        uses: go-task/setup-task@v2
        with:
          version: 3.x
      - name: run tests
        uses: docker://golang:1.24-bullseye
        with:
          args: task build lint bench cover-console-out
