name: Run Tests

on:
  push:
    branches:
      - master
      - main
      - dev
      - "dev**"
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - master
      - main
      - dev
      - "dev**"
      - "releases/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run tests
        uses: docker://golang:1.22-bullseye
        with:
          args: make build lint bench cover-console-out

