name: Run Tests

on:
  push:
    branches: 
      - main
      - 'releases/**'
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches: 
      - main
      - 'releases/**'
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: deploy container
      uses: docker://golang:1.18rc1-bullseye
    - name: run tests
      run: make test
      working-directory: /github/workspace
  
