name: Run Tests

on:
  push:
    branches:
      - main
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main
      - "releases/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run tests
        uses: docker://golang:rc
        with:
          args: make test

